services:
  lio_sam:
    build: .
    image: lio_sam_6axis_built
    container_name: lio_sam_6axis
    network_mode: "host"
    environment:
      - DISPLAY=host.docker.internal:0.0
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/workspace
      - ./src/simpleGpsOdom_patched.cpp:/root/workspace/src/LIO_SAM_6AXIS/LIO-SAM-6AXIS/src/simpleGpsOdom.cpp:ro
      - ./src/LIO-SAM-6AXIS-src/mapOptmizationGps.cpp:/root/workspace/src/LIO_SAM_6AXIS/LIO-SAM-6AXIS/src/mapOptmizationGps.cpp:ro
    working_dir: /workspace
    # To run without GNSS (default):
    # command: /bin/zsh -c "./run_lio_sam.sh"
    # To run WITH GNSS (make sure you converted the bags with the GNSS scripts first!):
    command: /bin/zsh -c "source /opt/ros/melodic/setup.zsh && cd /root/workspace && catkin build && source devel/setup.zsh && cd /workspace && ./scripts/run_lio_sam_gnss.sh"
